version: "3"
services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    restart: always

  nodered:
    image: nodered/node-red-docker
    restart: always
    volumes:
      - ./node-red/data:/data
    ports:
      - 1880:1880
    command: [sh, -c, "cd /data && npm i node-red-contrib-influxdb node-red-dashboard && cd /usr/src/node-red && npm start -- --userDir /data"]